export enum ParameterType {
  CUSTOM,
  CONNECTED_SOCKET,
  MESSAGE_BODY,
  MESSAGE_ACK,
  SOCKET_QUERY_PARAM,
  SOCKET_IO,
  SOCKET_ID,
  SOCKET_REQUEST,
  SOCKET_ROOMS,
  NAMESPACE_PARAMS,
  NAMESPACE_PARAM,
}
